= SolarDoc 🌌✨

SolarDoc is a dynamic online editor which allows you to create beautiful presentations using AsciiDoc in your browser. Collaborate with your colleagues and friends in the online editor and freely share your work with anyone! 

== Problem & Background

=== Given Situation

There is no collaborative environment for creating presentations using AsciiDoc. As such, it is difficult to efficiently develop presentations. Currently, there are tools & plugins available to render real-time AsciiDoc and AsciiDoc presentations using revael.js, but they either lack functionality or require monthly license payments. As such they are unsuitable for students and teachers given the college environment. 

=== Potential for improvement

- Better code editor for writing AsciiDoc
- Better UI for viewing presentation slides and nested slides
- Ability to easily work collaboratively on presentations
- More accessibility for students and teachers
- Ability to share files and with anyone using share links

== Goals




== Potential & Risks



== Roadmap & Planning


