// Generated by '@import-meta-env/typescript'

interface ImportMetaEnv {
  readonly DEV_BACKEND_HOST: string;
  readonly DEV_BACKEND_PORT: string;
  readonly PROD_BACKEND_PORT: string;
  readonly PROD_BACKEND_HOST: string;
}

interface ImportMeta {
  readonly env: ImportMetaEnv;
}
